#include "GResourceExporter.hpp"
#include "SvgOptimiser.hpp"
#include "PngExporter.hpp"
#include "CurvzLog.hpp"
#include <filesystem>
#include <fstream>
#include <sstream>
#include <functional>
#include <map>
#include <set>

namespace fs = std::filesystem;
namespace Curvz {

// ── Directory helpers ─────────────────────────────────────────────────────────

static bool ensure_dir(const std::string& path) {
    std::error_code ec;
    fs::create_directories(path, ec);
    if (ec) {
        LOG_ERROR("GResourceExporter: cannot create dir '{}': {}", path, ec.message());
        return false;
    }
    return true;
}

static bool write_text(const std::string& path, const std::string& content) {
    std::ofstream f(path);
    if (!f.is_open()) {
        LOG_ERROR("GResourceExporter: cannot write '{}'", path);
        return false;
    }
    f << content;
    return true;
}

// ── gresource.xml ─────────────────────────────────────────────────────────────
// References scalable/ (SVG) and 16x16/ (PNG fallback) per GTK convention.

static std::string build_gresource_xml(
        const std::vector<ExportEntry>& entries,
        const std::string& prefix)
{
    // Collect categories and icons
    // category → list of icon names
    std::map<std::string, std::vector<std::string>> by_cat;
    for (const auto& e : entries) {
        if (!e.include || !e.doc) continue;
        if (e.doc->export_name.empty() || e.doc->export_category.empty()) continue;
        std::string base = e.doc->export_name;
        if (base.size() > 9 && base.substr(base.size() - 9) == "-symbolic")
            base = base.substr(0, base.size() - 9);
        by_cat[e.doc->export_category].push_back(base);
    }

    std::ostringstream out;
    out << "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n";
    out << "<gresources>\n";

    // scalable/<category>/ entries
    for (const auto& [cat, names] : by_cat) {
        out << "  <gresource prefix=\"" << prefix << "/icons/scalable/" << cat << "\">\n";
        for (const auto& name : names)
            out << "    <file preprocess=\"xml-stripblanks\">" << name << "-symbolic.svg</file>\n";
        out << "  </gresource>\n";
    }

    // 16x16/<category>/ entries
    for (const auto& [cat, names] : by_cat) {
        out << "  <gresource prefix=\"" << prefix << "/icons/16x16/" << cat << "\">\n";
        for (const auto& name : names)
            out << "    <file>" << name << "-symbolic.png</file>\n";
        out << "  </gresource>\n";
    }

    out << "</gresources>\n";
    return out.str();
}

// ── index.theme ───────────────────────────────────────────────────────────────
// For system-wide installation under /usr/share/icons/<theme_name>/

static std::string build_index_theme(
        const std::string& theme_name,
        const std::string& theme_comment,
        const std::set<std::string>& categories)
{
    // Collect all directory entries
    std::vector<std::string> dirs;
    dirs.push_back("scalable/actions");  // always list scalable first
    for (const auto& cat : categories) {
        if (cat != "actions")
            dirs.push_back("scalable/" + cat);
    }
    static constexpr int k_sizes[] = { 16, 24, 32, 48, 64, 128, 256 };
    for (int sz : k_sizes) {
        std::string s = std::to_string(sz);
        for (const auto& cat : categories)
            dirs.push_back(s + "x" + s + "/" + cat);
    }

    std::ostringstream out;
    out << "[Icon Theme]\n";
    out << "Name=" << theme_name << "\n";
    out << "Comment=" << theme_comment << "\n";
    out << "Inherits=hicolor\n";
    out << "Directories=";
    for (int i = 0; i < (int)dirs.size(); ++i) {
        if (i > 0) out << ",";
        out << dirs[i];
    }
    out << "\n\n";

    // Scalable sections
    for (const auto& cat : categories) {
        out << "[scalable/" << cat << "]\n";
        out << "Size=48\n";
        out << "MinSize=8\n";
        out << "MaxSize=512\n";
        out << "Type=Scalable\n";
        out << "Context=" << cat << "\n\n";
    }

    // Fixed-size sections
    for (int sz : k_sizes) {
        std::string s = std::to_string(sz);
        for (const auto& cat : categories) {
            out << "[" << s << "x" << s << "/" << cat << "]\n";
            out << "Size=" << sz << "\n";
            out << "Type=Fixed\n";
            out << "Context=" << cat << "\n\n";
        }
    }

    return out.str();
}

// ── README.md ─────────────────────────────────────────────────────────────────

static std::string build_readme(
        const std::string& theme_name,
        const std::string& output_dir_name,
        const std::string& prefix)
{
    std::ostringstream out;
    out << "# " << theme_name << " Icon Theme\n\n";
    out << "Generated by [Curvz](https://github.com/curvz) — professional SVG icon editor.\n\n";

    out << "## Contents\n\n";
    out << "```\n";
    out << output_dir_name << "/\n";
    out << "  scalable/<category>/<name>-symbolic.svg   # Vector icons (primary)\n";
    out << "  16x16/<category>/<name>-symbolic.png      # PNG fallback\n";
    out << "  24x24/  32x32/  48x48/  64x64/            # Additional PNG sizes\n";
    out << "  128x128/  256x256/                         # High-res PNG sizes\n";
    out << "  gresource.xml                              # GLib resource bundle\n";
    out << "  index.theme                                # Freedesktop theme descriptor\n";
    out << "  README.md                                  # This file\n";
    out << "```\n\n";

    out << "---\n\n";

    out << "## Option 1 — Bundle into your app as a GResource (recommended)\n\n";
    out << "This embeds the icons directly in your application binary.\n";
    out << "No system installation required. Icons are loaded at runtime via GTK.\n\n";

    out << "### Step 1 — Copy files into your project\n\n";
    out << "Copy `scalable/`, `16x16/`, and `gresource.xml` into your project,\n";
    out << "or merge them into your existing `*.gresource.xml`.\n\n";

    out << "### Step 2 — Compile the GResource bundle\n\n";
    out << "**With CMake:**\n\n";
    out << "```cmake\n";
    out << "find_program(GLIB_COMPILE_RESOURCES glib-compile-resources REQUIRED)\n\n";
    out << "add_custom_command(\n";
    out << "  OUTPUT  ${CMAKE_CURRENT_BINARY_DIR}/icons.c\n";
    out << "  COMMAND ${GLIB_COMPILE_RESOURCES}\n";
    out << "          --target=${CMAKE_CURRENT_BINARY_DIR}/icons.c\n";
    out << "          --generate-source\n";
    out << "          ${CMAKE_CURRENT_SOURCE_DIR}/gresource.xml\n";
    out << "  DEPENDS ${CMAKE_CURRENT_SOURCE_DIR}/gresource.xml\n";
    out << "  WORKING_DIRECTORY ${CMAKE_CURRENT_SOURCE_DIR}\n";
    out << ")\n\n";
    out << "target_sources(MyApp PRIVATE ${CMAKE_CURRENT_BINARY_DIR}/icons.c)\n";
    out << "```\n\n";

    out << "**With Meson:**\n\n";
    out << "```meson\n";
    out << "icons_res = gnome.compile_resources(\n";
    out << "  'icons',\n";
    out << "  'gresource.xml',\n";
    out << "  source_dir: meson.current_source_dir(),\n";
    out << ")\n";
    out << "executable('myapp', sources + icons_res, ...)\n";
    out << "```\n\n";

    out << "**Manually:**\n\n";
    out << "```bash\n";
    out << "glib-compile-resources --generate-source --target=icons.c gresource.xml\n";
    out << "# Then compile icons.c into your build.\n";
    out << "```\n\n";

    out << "### Step 3 — Register the resource prefix at runtime\n\n";
    out << "Call this once before your GTK application window is shown:\n\n";
    out << "```c\n";
    out << "/* C */\n";
    out << "gtk_icon_theme_add_resource_path(\n";
    out << "    gtk_icon_theme_get_for_display(gdk_display_get_default()),\n";
    out << "    \"" << prefix << "/icons\"\n";
    out << ");\n";
    out << "```\n\n";
    out << "```cpp\n";
    out << "// C++ / gtkmm\n";
    out << "auto theme = Gtk::IconTheme::get_for_display(Gdk::Display::get_default());\n";
    out << "theme->add_resource_path(\"" << prefix << "/icons\");\n";
    out << "```\n\n";

    out << "### Step 4 — Use the icons\n\n";
    out << "```cpp\n";
    out << "// gtkmm — by icon name (without -symbolic suffix; GTK appends it automatically)\n";
    out << "auto image = Gtk::make_managed<Gtk::Image>();\n";
    out << "image->set_from_icon_name(\"edit-copy\");   // loads edit-copy-symbolic\n\n";
    out << "// Or with explicit symbolic lookup:\n";
    out << "image->set_from_icon_name(\"edit-copy-symbolic\");\n";
    out << "```\n\n";
    out << "GTK recolours symbolic icons automatically to match the current theme's\n";
    out << "foreground colour. No manual colour management is needed.\n\n";

    out << "---\n\n";

    out << "## Option 2 — Install system-wide as an icon theme\n\n";
    out << "This makes the icons available to any application on the system.\n\n";

    out << "```bash\n";
    out << "# User install (no root required)\n";
    out << "mkdir -p ~/.local/share/icons/" << theme_name << "\n";
    out << "cp -r scalable 16x16 24x24 32x32 48x48 64x64 128x128 256x256 index.theme \\\n";
    out << "    ~/.local/share/icons/" << theme_name << "/\n";
    out << "gtk-update-icon-cache ~/.local/share/icons/" << theme_name << "\n\n";
    out << "# System install (requires root)\n";
    out << "sudo cp -r scalable 16x16 24x24 32x32 48x48 64x64 128x128 256x256 index.theme \\\n";
    out << "    /usr/share/icons/" << theme_name << "/\n";
    out << "sudo gtk-update-icon-cache /usr/share/icons/" << theme_name << "\n";
    out << "```\n\n";
    out << "After installation, select `" << theme_name << "` in your desktop's\n";
    out << "appearance settings, or set it programmatically:\n\n";
    out << "```bash\n";
    out << "gsettings set org.gnome.desktop.interface icon-theme '" << theme_name << "'\n";
    out << "```\n\n";

    out << "---\n\n";

    out << "## Icon naming\n\n";
    out << "All icons follow the [Freedesktop Icon Naming Specification]";
    out << "(https://specifications.freedesktop.org/icon-naming-spec/latest/).\n";
    out << "Symbolic variants carry the `-symbolic` suffix and use `currentColor`\n";
    out << "so they recolour automatically with the GTK theme.\n\n";

    out << "---\n\n";
    out << "*Generated by Curvz*\n";

    return out.str();
}

// ── Main export ───────────────────────────────────────────────────────────────

ExportResult export_theme(
        const std::vector<ExportEntry>& entries,
        const std::string& output_dir,
        const std::string& theme_name,
        const std::string& theme_comment,
        std::function<void(int,int,const std::string&)> progress_cb)
{
    ExportResult result;
    result.output_dir = output_dir;

    // Count exportable icons
    std::vector<const ExportEntry*> valid;
    for (const auto& e : entries) {
        if (!e.include || !e.doc) continue;
        if (e.doc->export_name.empty() || e.doc->export_category.empty()) {
            result.icons_skipped++;
            continue;
        }
        valid.push_back(&e);
    }

    if (valid.empty()) {
        result.error_message = "No icons to export. Assign a name and category to each icon in the inspector.";
        return result;
    }

    if (!ensure_dir(output_dir)) {
        result.error_message = "Cannot create output directory: " + output_dir;
        return result;
    }

    // Collect categories used
    std::set<std::string> categories;
    for (const auto* ep : valid)
        categories.insert(ep->doc->export_category);

    // Create all output subdirectories
    static constexpr int k_sizes[] = { 16, 24, 32, 48, 64, 128, 256 };
    for (const auto& cat : categories) {
        if (!ensure_dir(output_dir + "/scalable/" + cat)) {
            result.error_message = "Cannot create scalable/" + cat;
            return result;
        }
        for (int sz : k_sizes) {
            std::string s = std::to_string(sz);
            if (!ensure_dir(output_dir + "/" + s + "x" + s + "/" + cat)) {
                result.error_message = "Cannot create " + s + "x" + s + "/" + cat;
                return result;
            }
        }
    }

    // Export each icon
    const int total = (int)valid.size();
    for (int i = 0; i < total; ++i) {
        const CurvzDocument& doc = *valid[i]->doc;
        const std::string& name  = doc.export_name;
        const std::string& cat   = doc.export_category;
        // Strip trailing -symbolic if user already included it — we always append it.
        std::string base = name;
        if (base.size() > 9 && base.substr(base.size() - 9) == "-symbolic")
            base = base.substr(0, base.size() - 9);
        const std::string stem   = base + "-symbolic";

        if (progress_cb) progress_cb(i, total, name);

        // SVG
        std::string svg_path = output_dir + "/scalable/" + cat + "/" + stem + ".svg";
        std::string svg = optimise_svg(doc);
        if (!write_text(svg_path, svg)) {
            LOG_ERROR("GResourceExporter: failed to write SVG for '{}'", name);
            continue;
        }

        // PNGs
        bool any_failed = false;
        for (int sz : k_sizes) {
            std::string s   = std::to_string(sz);
            std::string png = output_dir + "/" + s + "x" + s + "/" + cat + "/" + stem + ".png";
            if (!export_png(doc, png, sz)) {
                LOG_ERROR("GResourceExporter: failed to write {}px PNG for '{}'", sz, name);
                any_failed = true;
            }
        }
        if (!any_failed)
            result.icons_written++;
        else
            result.icons_skipped++;
    }

    if (progress_cb) progress_cb(total, total, "");

    // Determine resource prefix from theme name (lowercase, no spaces)
    std::string prefix = "/" + theme_name;
    for (char& c : prefix) {
        if (c == ' ') c = '-';
        c = (char)std::tolower((unsigned char)c);
    }

    // gresource.xml
    std::string gres = build_gresource_xml(entries, prefix);
    write_text(output_dir + "/gresource.xml", gres);

    // index.theme
    std::string theme = build_index_theme(theme_name, theme_comment, categories);
    write_text(output_dir + "/index.theme", theme);

    // README.md
    std::string readme = build_readme(
        theme_name,
        fs::path(output_dir).filename().string(),
        prefix);
    write_text(output_dir + "/README.md", readme);

    LOG_INFO("GResourceExporter: exported {} icons to '{}'",
             result.icons_written, output_dir);

    result.success = (result.icons_written > 0);
    if (!result.success && result.error_message.empty())
        result.error_message = "All icons failed to write. Check log for details.";

    return result;
}

} // namespace Curvz
